### ISSUE TITLE
Function request for bit_vector class: == or != operator

### ISSUE THREAD

**Issue by mariehoffmann** [xxsds/sdsl-lite#10]
To store in seqan3 an aligned sequence (alphabet symbols plus gap symbol) efficiently, only the gap-free sequence are stored and a bit vector (bit_vector_il.hpp) indicating gap positions. Two aligned sequences are equal if their alphabet sequences and their gap vectors are equal. Currently there are no boolean operators implemented for the bit vector as a whole. One has to parse it with the provided begin/end iterators and compare element-wise. 
I wonder if there is a more efficient way knowing the intrinsics of the bit vector implementation. If so, it would be nice if the bit_vector class could provide then the boolean equality or inequality operator.

**Comment by mpetri** [comment]
I added those operators. However, I didn't test it. If you could checkout the current master and check if it works that would be awesome.

**Comment by mariehoffmann** [comment]
It worked! But I decided now to use the sd_vector, since the bit vector will be mostly filled sparsely. So, I would need the boolean equality operators for the sd_vector class :|
