### ISSUE TITLE
Swap function for bit_vector_il

### ISSUE THREAD

**Issue by mariehoffmann** [xxsds/sdsl-lite#12]
I need a swap operator for the bit_vector_il. In the orignal module there is one https://github.com/simongog/sdsl/blob/master/include/sdsl/bit_vector_interleaved.hpp. Will both modules be synchronized soon?

**Comment by mpetri** [comment]
what is the swap used for? Usually std::swap and a move operator works the same?

**Comment by mariehoffmann** [comment]
I need to swap a class instance and its helper structures including the bit_vector. Both instances need to stay alive. Move destroys one, right? Of course I can use temporaries to get around. Or do I oversee sth?

**Comment by mpetri** [comment]
that's what `std::swap`: http://en.cppreference.com/w/cpp/algorithm/swap 

could be that you have to have to reassign the rank_supports with set_vector but I'm not sure.

**Comment by mariehoffmann** [comment]
std::swap can be used whenever the class is move constructable with a noexcept. Right now the compiler does not complain, so I guess that's the case. And yes, probably I have to re-init the helper structures like rank_support.
