### ISSUE TITLE
Unexpected behaviour of rank_support_v5's move constructor

### ISSUE THREAD

**Issue by mariehoffmann** [xxsds/sdsl-lite#15]
Move construction in initializer list with rank_support_v5 (`rs`) as a class member does not seem to copy the underlying bit_vector pointer(?). Accessing the rank of the move constructed leads to a segmentation fault, its size remains 0.

Our move constructor:

    constexpr aligned_sequence(aligned_sequence && rhs) : gap_symbol(std::move(rhs.gap_symbol)), gap_vector(std::move(rhs.gap_vector)), rs(std::move(rhs.rs)), sequence(std::move(rhs.sequence))
    {
        //rs = std::move(rhs.rs);
        //rs.set_vector(&gap_vector);
        std::cout << "mv construct: gap_vector.size = " << gap_vector.size() << ", sequence.size = " << sequence.size() << ", rs.size = " << rs.size() << std::endl;
    } 

Member variables of rhs before move:
`14: assign: gap_vector.size = 5, sequence.size = 4, rs.size = 5`
Member variables of *this after move: 
`14: mv construct: gap_vector.size = 5, sequence.size = 4, rs.size = 0`

Same is true when using move assign instead (see commented line). Workaround is to use the set_vector function. 
Strangely, testing move assignment and construction of rank_support_v5 separately, works as expected:
```
    // rank support test
    b1 = sdsl::bit_vector(2, 0);
    b2 = sdsl::bit_vector(1, 1);
    sdsl::rank_support_v5<> rs1(&b1);
    sdsl::rank_support_v5<> rs2(&b2);
    // mv assign
    sdsl::rank_support_v5<> rs3 = std::move(rs1);
    EXPECT_EQ(2, rs3.size());
    EXPECT_EQ(0, rs3.rank(0));
    EXPECT_EQ(0, rs3.rank(1));
    // mv construct
    sdsl::rank_support_v5<> rs4(std::move(rs2));
    EXPECT_EQ(1, rs4.size());
    EXPECT_EQ(1, rs4.rank(1));
```

**Comment by mpetri** [comment]
The reason we are doing this is the fact that a class usually has 2 members. The bitvector and the rank_support structure. 

In a move constructor you would first move the bit_vector object and then the rank_support. However, the rank_support requires a pointer to the actual bit_vector object of the class. For example:

```
class test {
     bit_vector A;
     rank_support_v5<> A_rank;
}
```
lets say you have a move constructor for the `test` class:

```
test::test(test&& o) {
   A = std::move(o.A);
   A_rank = std::move(o.A_rank);
}
```
however the pointer of `A` in the class instance of `A_rank` has to be the address of `A` inside the class and not the pointer of `o.A`. Thus, you have to call `set_vector` after moving `o.A_rank`. 

We have discussed this extensively and don't see any "nicer" way to implement this.

**Comment by mariehoffmann** [comment]
Understand. And since `bit_vector` and `rank_support` are supposed to be used also independent from each other, it is up to the user how to use them combined.
