### ISSUE TITLE
very basic bit_vector usage broken

### ISSUE THREAD

**Issue by h-2** [xxsds/sdsl-lite#16]
I have this very simple program:

```cpp
#include <sdsl/int_vector.hpp>
#include <sdsl/rank_support_v5.hpp>
#include <sdsl/select_support_mcl.hpp>

#include <iostream>

int main()
{
    for (auto pair : {std::make_tuple(100ul, 10000ul), std::make_tuple(1000ul, 1000ul), std::make_tuple(10000ul, 100ul)})
    {
        auto count = std::get<0>(pair);
        auto size = std::get<1>(pair);
        std::cout << "COUNT: " << count << "\tSIZE: " << size << '\n';

        sdsl::bit_vector bivi;

        bivi.resize(1);
        for (unsigned i = 0; i < count; ++i)
        {
            bivi.resize(bivi.size() + size); // enlarge by 10
            bivi[bivi.size() - 1] = 1;     // set last to 1
        }

//         sdsl::rank_support_v5<> rank_support(&bivi);
//         sdsl::select_support_mcl<1> select_support(&bivi);

        for (unsigned i = 0; i < bivi.size(); ++i)
        {
            if (bivi[i] && (i % 100 != 0))
                std::cout << i << " " << bivi[i] << '\n';
        }

    }
}
```
It has three loop iterations and does `count` times resizes of size `size`, always setting the last bit to 1. Obviously all positions with set bits should be dividable by 100.  The expected output is:
```
COUNT: 100      SIZE: 10000
COUNT: 1000     SIZE: 1000
COUNT: 10000    SIZE: 100
```
Clang actually produces this.
But any invocation of g++6, g++7 or g++8 produces:
```
COUNT: 100      SIZE: 10000
COUNT: 1000     SIZE: 1000
7424 1
12512 1
COUNT: 10000    SIZE: 100
1344 1
7424 1
116640 1
117640 1
119640 1
... (many more "errors")
```
That is, the first loop iteration works, than the second doesn't (but only with a few errors), and the third produces completely wrong results. If you skip the first iteration, than the second works. I assume there is some bug in your memory management code that relates to some state being saved, or some areas not being zero'd properly.
Peculiarly, uncommenting range and select support actually "breaks" the existing bit_vector even more, i.e. there will already be many errors in the second iteration. AND if they are uncommented, than the clang program is also broken.

It took me considerable time to track this down, because it doesn't happen on singular usage of a bitvector. I would be happy about any and all feedback as this effects many data structures in seqan3 that are now using bit_vectors.
Thanks!

**Comment by h-2** [comment]
@mariehoffmann this likely effects your PR, as well.

**Comment by mariehoffmann** [comment]
Had a similar issue, but did not suspect the bit_vector code to be erroneous and did not test further. I had a test case in which `bit_vector.resize()` left the its size unchanged. Looking very superficially into the `resize` function, I found that resizing is only done when a certain difference threshold is exceeded (see lines 760 and 761 in memory_management.hpp). E.g. changing from 10 to 12 would not change the internal size, since ((10 + 63 >> 6) << 3) = 4 =  (12 + 63 >> 6) << 3, but 15 as input would: (15 + 63 >> 6) << 3 = 8. Does this explain your output?
I use now a variable for the actual size of the bit_vector.

**Comment by mpetri** [comment]
do all the tests currently pass? I had similar issues but didn't have to the time to track down what is going on.

@mariehoffmann: the `bit_vector` is at least one 64 bit word long.

**Comment by h-2** [comment]
@mpetri Thanks for your response. Which tests do you mean? Your library tests? I don't know...
Do you have nightly-builds or continuous integration? travis is really easy to set up :)

I have done some more research, and it seems to be .resize() that is always broken. Even if I only do a single resize to the final size and then flip single bits, it gets broken. However, if I instead re-assign a new bit-vector of the final size it seems to work.

@mariehoffmann This i could or could not be related. There are two levels of resize here, the "outer-resize", this relates to the size we see and an "inner-resize" that relates to the memory actually allocated (which comes in blocks of at least a byte, but usually 64bit).

**Comment by mpetri** [comment]
I don't think travis is set up for this repo yet. Can you run `make test-full-sdsl` and see how it goes.

I agree that there might be something wrong with the `bit_vector` sizing. I will investigate

**Comment by h-2** [comment]
>  Can you run make test-full-sdsl and see how it goes.

Cmake fails to run cleanly, produces hundreds of errors about policy changes.. Adding 
```cmake
cmake_policy(SET CMP0002 old)
cmake_policy(SET CMP0007 old)
```
reduces the errors, but it still won't build. Are you sure the scripts work with current cmake versions?

**Comment by simongog** [comment]
Thanks for reporting.
As far as I remember, resize does not initialize the appended bits to zeros. I think you make this assumption in your program.

**Comment by h-2** [comment]
@simongog Thanks for responding, Simon! Yes, I assumed that it did, because that's what the STL vectors do, as well. I had also tried to use `.resize(size, init_value)` to make sure that it was initialised, but this interface wasn't available...

**Comment by mpetri** [comment]
Maybe it makes sense to be consistent with the standard library here and automatically init to 0?

**Comment by simongog** [comment]
Ok. This will be done.

**Comment by h-2** [comment]
Great! If you are worried about a possible performance impact in cases where you know you absolutely don't need it, you could offer:
```cpp
.resize(size);              // inits with 0
.resize(size, value);       // inits with value
.resize(size, std::ignore); // special overload that skips init
```
(although this is not important for us)

**Comment by cpockrandt** [comment]
If noone disagrees, I'll take care of this issue and try to adapt the vectors to implement the STL container concept. The idea by @h-2 sounds good to me! :)

**Comment by cpockrandt** [comment]
@simongog I extended the int_vector on the retreat to fulfill the random access concept and finish it now to also support reserve(), capacity(), shrink_to_fit() and resize() as specified by the [std::vector](http://en.cppreference.com/w/cpp/container/vector#Capacity).

Since this results in quite a lot of changes for the int_vector with respect to storage behavior (i.e. reserving unneccessary storage for better amortized running time), I wanted to check back with you whether you are open to these changes :-)

**Comment by cpockrandt** [comment]
I think this issue can be closed now.
