### ISSUE TITLE
mutability of the bit-vectors other than bit_vector and their support data structures

### ISSUE THREAD

**Issue by h-2** [xxsds/sdsl-lite#18]
Or am I overlooking something? Or maybe it's not really a vector, but can only be created from other vectors?

On a more general note: I know from own experience that it's a pain to implement, but it would really help if the SDSL's vectors provided the same interfaces as std::vector. Comparing implementations and benchmarking of data structures gets very cumbersome if one has to add quirks everywhere to accommodate for custom behaviour and lack of overloads...

Thank you very much!

**Comment by mpetri** [comment]
the `int_vector` in the `int-vector-improvements` branch should have the same features as a regular `std::vector` including `capacity()` and `push_back` and `shrink_to_fit`.

In general, the `sd_vector` is designed to be immutable.

**Comment by h-2** [comment]
> the int_vector in the int-vector-improvements branch should have the same features as a regular std::vector including capacity() and push_back and shrink_to_fit.

That's cool :+1: 

> In general, the sd_vector is designed to be immutable.

Ah, ok, that's good to know. I know the cheat-sheet says:
```
bit_vector equals int_vector<1> and is therefore dynamic.
...
Each bitvector can be constructed out of a bit_vector object.
```

But I still stumbled over this, because in usual c++ terminology `vector` always implies a dynamic data structure and the way the "vectors" are listed in the cheat-sheet make them seem interchangeable.
Also there is real benefit to the vectors having the same interface for generic programming. Are there algorithmic reasons for `sd_vector` not being mutable? If it just cannot be dynamic without actually reconstructing the whole thing on every modifying operation, maybe calling it `sd_array` or `sd_bitset` would be clearer?

Thanks for your replies!

**Comment by mpetri** [comment]
You can always use a `using sd_array = sd_vector` type alias if you don't like the names. I generally prefer the name `vector` as most of these are compressed bit-"vectors".

**Comment by h-2** [comment]
I know I can give it an alias, it was more about ease of using the library, but that's of course up to you. Anyway, naming is less important than actual interfaces.

Are there (algorithmic) reasons the sd_vector has to be immutable? Also what about the support data structures? Especially for the regular bit-vector, I imagine one *could* resize the support data structures with the vector and just recompute on the new entries as the previous blocks and super-blocks remain unchanged...

**Comment by mpetri** [comment]
There are algorithmic reasons:

1. The sd_vector is essentially an increasing sequence of integers. Each number is split up into a `low` part and a `high` part. The split is determined by the size of the bitvector `n` and the number of elements `m`. So if you add one element (the next 1 bit position) `m` increases by `1` and `n` can potentially increase by a lot. So, the split could change and everything has to be recomputed to get the space guarantees of the `sd_vector`.

2. The `high` part of the `sd_vector` is itself another bitvector with a which has a `select_support` attached to it which needs to be adjusted.

3. The `select_support_mcl` and `rank_support_v5` of a regular bit vector probably can support `append` in amortized constant time but this is not implemented and would require serious re-engineering. 

So for a regular bit_vector this might be possible but for the `sd_vector` it is not. In general most structures in `sdsl` are designed for immutability and speed. There are other libraries such as https://github.com/xxsds/DYNAMIC which provide dynamic versions of some of these structures in `sdsl` which tend to be (much) slower than what is provided in sdsl.
