### ISSUE TITLE
int_vector_trait<1> ?

### ISSUE THREAD

**Issue by h-2** [xxsds/sdsl-lite#19]
The bit_vectors use the int vector traits of the dynamic int_vector which defaults to underlying blocks of size uint64_t. Would it not make sense to use uint8_t for the bitvectors? I tried to benchmark this quickly, but there seems to be some assumptions in the int_vector_iterator that make it not trivial to adapt.

**Comment by mpetri** [comment]
Is the 56 extra bits a problem?

**Comment by h-2** [comment]
No, I was thinking that reading and writing bytes might be faster than words, but I TBH I don't know if that's measurable. However I assume that reading and writing bytes will defintely reduce the synchronisation overhead in multi-threaded environments.
Anyway, it's not so important, I was just wondering.

**Comment by mpetri** [comment]
If you access some memory address a whole cache line is loaded anyway so I don't think there would be a measurable difference.
