### ISSUE TITLE
Usage: How to construct a suffix tree of type cst_sada?

### ISSUE THREAD

**Issue by mariehoffmann** [xxsds/sdsl-lite#20]
Do I use `construct(.., cst_tag)` from `construct.hpp`? But how do I toggle that I want the sada (Sadakane) algorithm to be applied? Or do I directly call the constructor in `cst_sada.hpp` with a `cache_config` containing the file map for the data structure storage?
Assume `infile_text` and `outfile_cst` are valid file paths, would a sound usage look like this?

    sdsl::tMSS filemap = {{sdsl::conf::KEY_TEXT, infile_text}, {sdsl::conf::KEY_CST, outfile_cst}};
    sdsl::cache_config config{false, tmp_dir, "", filemap};
    construct(/*t_index&*/ idx?, /*const std::string&*/ file, /*cache_config&*/ config, /*uint8_t num_bytes*/ 1, sdsl::cst_tag());

or just `sdsl::cst_sada cst(config);`. 
I am a bit confused, because in the cheat sheet the first argument of `construct` is already an instance of the data structure to be built and online examples refer to another version of the library.

Thanks in advance!

**Comment by mpetri** [comment]
Check out this example: https://github.com/xxsds/sdsl-lite/blob/master/examples/cst-node-child-iterator.cpp
