### ISSUE TITLE
raise warning levels

### ISSUE THREAD

**Issue by h-2** [xxsds/sdsl-lite#26]
It would be great if you could raise the warning levels on SDSL so consumers of the library can do so, as well. Not checking for warnings means that everyone else must also deactivate these checks which in turns perpetuates mistakes through other projects.

A good solution for warnings can be found here:
https://github.com/ericniebler/range-v3/blob/master/cmake/ranges_flags.cmake

A simpler approach that already covers most things would be to set the following for your tests:
 * for Clang: `-pedantic -Werror -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic`
 * for GCC: `-pedantic -Werror -Wall -Wextra -Wconversion`

An example of where our code now always triggers warnings in SDSL, including fix is #17 .

In case where your code triggers warnings, but you cannot fix the situation (or at least not in a feasible amount of time) you can locally deactivate the warning in that code segment. This would at least permit others to activate the warning for their project.

Thank you very much!

**Comment by simongog** [comment]
Ok.

**Comment by eseiler** [comment]
We are currently testing for `-pedantic -Wall -Wextra -Werror`.
`-Wconversion` is quite the effort, this may be done when we introduce it to seqan.
