### ISSUE TITLE
Attach user-defined data with each string in CST or CSA

### ISSUE THREAD

**Issue by sanjosh** [xxsds/sdsl-lite#29]
Is there a way to attach user-defined custom info to each string which were inserted into the CST or CSA ?  For example, if I find a pattern in the CST or CSA, I would like to return a document_id from which it originally came.

**Comment by mpetri** [comment]
You are most likely looking doing document retrieval. There is lots of work on the topic. Checkout the `benchmark/document_retrieval/src` directory for some solutions. There is more recent work on this which is not included in the library though.
