### ISSUE TITLE
Efficient sd_vector comparison

### ISSUE THREAD

**Issue by mariehoffmann** [xxsds/sdsl-lite#30]
In the sd_vector class there is no operator==. Looking into https://github.com/simongog/sdsl/blob/master/include/sdsl/sd_vector.hpp there is an implementation, but it only compares addresses. Is that correct?
If I want to compare two equally sized sd_vectors (1 bits at same positions), is there are a more efficient way, i.e. sublinear of `m`, where `m` is the number of set bits (the naive way would compare the `select` positions for 1..m)?

**Comment by mpetri** [comment]
I added this operator 22 days ago see here: https://github.com/xxsds/sdsl-lite/blob/master/include/sdsl/sd_vector.hpp#L403

It should be as efficient as possible as it scans the 2m bits in the high part using 64 bit comparisons. Same for the low part.
