### ISSUE TITLE
Serialisation support via cereal

### ISSUE THREAD

**Issue by h-2** [xxsds/sdsl-lite#50]
As discussed with @simongog we will start implemented serialisation support via https://github.com/USCiLab/cereal.

This has the following advantages:
  * combinability with types from seqan and generic types from the standard library (everything can be serialised into a single file)
  * support for different formats (binary, endiannes-independent binary, json, xml)

The steps would be:
  1. add cereal as optional dependency to SDSL (header is auto-detected, no interference by cmake required) and define some names if cereal is not found.
  2. add cereal `load`/`save` or `serialize` member templates to those SDSL data structures that we currently use in SeqAN
  3. add it to the rest as well
  4. transform the current SDSL serialisation to appear exactly like the cereal serialisation and use the same functions; it will still work without cereal, but invoking it will be the same

**Comment by eseiler** [comment]
SDSL support can be activated by passing `-DSDSL_CEREAL=1` to cmake.
