### ISSUE TITLE
Memory leak fix leads to segfault

### ISSUE THREAD

**Issue by cpockrandt** [xxsds/sdsl-lite#61]
Since we now have Jenkins running, I noticed that the latest commit https://github.com/xxsds/sdsl-lite/commit/39fe6be0409ed95160dc38ac4a019710afb5f3b1 introduced a segfault ([Jenkins build](https://abibuilder.informatik.uni-tuebingen.de/jenkins/blue/organizations/jenkins/sdsl_ci_pipeline/detail/PR-44/1/pipeline/17/)). Jenkins is now triggered with every new pull request.

``make wt-byte-test_100a.txt search-bidirectional-test_empty.txt search-bidirectional-test-im_empty.txt``

When I revert the commit, it works fine. Can you look into it @eseiler?

The same might apply for ``wt-byte-test_100a`` but I had trouble reproducing it on my local machine. On a first glance it seems to be a similar issue and might be related.

I'm currently looking into the other tests failing (bidirectional-search and cst-byte/int).

**Comment by eseiler** [comment]
I'll have a look.

It's probably the changes in `memory_management.hpp`. But if you revert them, memory will probably leak

**Comment by cpockrandt** [comment]
Thanks! I don't suggest that we revert them. :) But I'm afraid that my worries were justified. It seems that not allocating memory for empty (interleaved) vectors does not work.

**Comment by eseiler** [comment]
Yes, I'll first re-check if the destructor / memory management does something weird if the size is 0 (in case I overlooked something there).
I'd think that an empty vector should get destroyed just as any other vector (and they don't leak).

**Comment by eseiler** [comment]
After some hours of gdb I proudly present #63
