### ISSUE TITLE
Weird size of the enc_vector

### ISSUE THREAD

**Issue by jendas1** [xxsds/sdsl-lite#69]
Hi,
I wanted to use `enc_vector<>` to have a smaller memory footprint, but it seems that the `enc_vector<>` is doing quite opposite. Boiling down to the MWE, even when all values are e.g. 1 (occupying only 1 bit if using `bit_compress`), its size (`size_in_mega_bytes`) is ~76 bits per value. It is even bigger that the `int_vector<>` (64 bits). Something is really weird here.

```cpp
#include <sdsl/int_vector.hpp>
#include <sdsl/enc_vector.hpp>
#include <sdsl/util.hpp>

using namespace sdsl;
using namespace sdsl::util;
using namespace std;


int main(int argc,char** argv) {
    uint64_t size = 1'000;
    int_vector<> vec(size,1);
    enc_vector<> encoded(vec);
    int_vector<> bit_compressed(vec);
    util::bit_compress(bit_compressed);
    cout << size_in_bytes(vec) << " B" << endl;
    cout << size_in_bytes(encoded) << " B" << endl;
    cout << size_in_bytes(bit_compressed) << " B" << endl;
    return EXIT_SUCCESS;
}
```
Output:
```
8008 B
9616 B
136 B
```

**Comment by mpetri** [comment]
The answer why this is happening is that the enc-vector encodes differences between numbers and the elias-gamma code is not "designed" to encode 0s so there is a special case where it uses 64 bits instead.

**Comment by jendas1** [comment]
Thanks for prompt answer and sorry for my late reply.
Encoding 0 using 64 bits is a very weird design choice, as smaller values should yield smaller vector, but the weirdness doesn't end there. When having alternate patter (0 1 0 1 0 1), the size improve, but the vector still requires 39 bits per element (1 being optimal).
```cpp
#include <sdsl/int_vector.hpp>
#include <sdsl/enc_vector.hpp>
#include <sdsl/util.hpp>

using namespace sdsl;
using namespace sdsl::util;
using namespace std;


int main(int argc,char** argv) {
    uint64_t size = 1'000;
    int_vector<> vec(size,1);
    for(int i=1; i<size;i+=2) {
        vec[i] = 0;
    }
    enc_vector<> encoded(vec);
    int_vector<> bit_compressed(vec);
    util::bit_compress(bit_compressed);
    cout << size_in_bytes(vec)*8/(double) size << " bits/el" << endl;
    cout << size_in_bytes(encoded)*8/(double) size << " bits/el" << endl;
    cout << size_in_bytes(bit_compressed)*8/(double) size << " bits/el" << endl;
    return EXIT_SUCCESS;
}

```
```
64.064 bits/el
39.04 bits/el
1.088 bits/el
```
I tried multiple patterns, and also default parameters (e.g. 0 1 2 3 ... 1000 that needs 42 bits per element) but everytime the bits per element was way above reasonable threshold. Can someone explain me what is the formula for computing approximate size & which data are well encoded using `enc_vector`?

**Comment by mpetri** [comment]
If you want to encode an array of non-increasing numbers you have to take the prefix sum to achieve good compression. So:

```
int_vector<> vec(size,1);
for(size_t i=1;i<vec.size();i++) vec[i] += vec[i-1];
enc_vector<> encoded(vec);
```

**Comment by mpetri** [comment]
Also, if that is the only thing you want to do I suggest you look at the `FastPFor` library instead.

**Comment by jendas1** [comment]
Sorry for misleading you, I made an error in the array generation and for the pattern 1 2 3 .. I get 1.4 bits per element.

**Comment by jendas1** [comment]
Update for others: The function `t_coder::encoding_length(i)` tells how much space value i will occupy.

**Comment by jendas1** [comment]
To summarize the inefficiencies of all encodings:
value 0 is represented using by excessive number of bits 77 bits and also all negative values are casted into an unsigned version which causes non optimal encoding (all negative values have the most significant bit set to 1).

**Comment by mpetri** [comment]
If you want to encode 0s just add 1 to all numbers before passing them into the enc-vector. If you want negative numbers use zig-zag encoding before passing into the enc-vector.

**Comment by jendas1** [comment]
The only problem is that already the `enc_vector` is delta encoding before storing the values.
```
 A generic immutable space-saving vector class for unsigned integers.
/*! A vector v is stored more space-efficiently by self-delimiting coding
 *  the deltas v[i+1]-v[i] (v[-1]:=0). Space of the structure and random
 *  access time to it can be controlled by a sampling parameter t_dens.
```

Therefore, when "preprocessing" the vector, it becomes quite messy as I would have to moreover invert the delta encoding.

**Comment by eseiler** [comment]
From what I gather, the behaviour is expected, and some alternatives were presented.
Please reopen if this is not the case.
