### ISSUE TITLE
version.hpp

### ISSUE THREAD

**Issue by h-2** [xxsds/sdsl-lite#7]
Hi Simon,

I was wondering if you could add a `version.hpp` that defines the current version of the sdsl?
Something like https://github.com/ericniebler/range-v3/blob/master/include/range/v3/version.hpp or https://github.com/seqan/seqan3/blob/master/include/seqan3/version.hpp 

It would make it easier for code including the SDSL to check if it is the right version.

Thanks,
Hannes

**Comment by mpetri** [comment]
This should probably be auto generated from the cmake files

**Comment by h-2** [comment]
> This should probably be auto generated from the cmake files

Since the SDSL is now header-only, it would be really good if using it would not require running cmake. IIRC there were other "dynamically created" headers that were replaced already, or not?

**Comment by cpockrandt** [comment]
Done in #33. Can be closed (I can't do it). :)
